"""
Advice Module — Report Generator
Produces professional consultant-style reports.

Output per assessment:
  advice_{profile}_{ts}.html       — bilingual HTML (TR/EN toggle + dark/light)
  advice_{profile}_{ts}_tr.pdf     — Turkish PDF
  advice_{profile}_{ts}_en.pdf     — English PDF

Report grouping regex: ^(advice_.+_\\d{8}_\\d{6})\\.(html|_tr\\.pdf|_en\\.pdf)$
"""

import os
import re as _re
from datetime import datetime

REPORTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'reports')
os.makedirs(REPORTS_DIR, exist_ok=True)


def _ts():
    return datetime.now().strftime('%Y%m%d_%H%M%S')


# ═══════════════════════════════════════════════════════════════════════════════
# Language helpers
# ═══════════════════════════════════════════════════════════════════════════════

_L = {
    'report_title':   {'en': 'AWS Well-Architected Assessment Report',
                       'tr': 'AWS Well-Architected Degerlendirme Raporu'},
    'tespitler':      {'en': 'Findings', 'tr': 'Tespitler'},
    'oneriler':       {'en': 'Recommendations', 'tr': 'Oneriler'},
    'olumlu':         {'en': 'Positive Findings', 'tr': 'Olumlu Tespitler'},
    'profile':        {'en': 'Profile', 'tr': 'Profil'},
    'account':        {'en': 'Account ID', 'tr': 'Hesap ID'},
    'date':           {'en': 'Assessment Date', 'tr': 'Degerlendirme Tarihi'},
    'summary':        {'en': 'Executive Summary', 'tr': 'Yonetici Ozeti'},
    'high_risk':      {'en': 'High Risk', 'tr': 'Yuksek Risk'},
    'medium_risk':    {'en': 'Medium Risk', 'tr': 'Orta Risk'},
    'low_risk':       {'en': 'Low Risk', 'tr': 'Dusuk Risk'},
    'positive':       {'en': 'Positive', 'tr': 'Olumlu'},
    'services':       {'en': 'Services Analyzed', 'tr': 'Analiz Edilen Servisler'},
    'pillar_scores':  {'en': 'WAFR Pillar Scores', 'tr': 'WAFR Sutun Skorlari'},
    'pillar':         {'en': 'Pillar', 'tr': 'Sutun'},
    'score':          {'en': 'Score', 'tr': 'Skor'},
    'findings':       {'en': 'Findings', 'tr': 'Tespitler'},
    'generated_by':   {'en': 'Generated by AWS ScanBox Analyzer — Advice Module',
                       'tr': 'AWS ScanBox Analyzer — Advice Modulu tarafindan olusturuldu'},
}


def _t(key, lang='tr'):
    return _L.get(key, {}).get(lang, key)


def _txt(item, lang='tr', key_en='text_en', key_tr='text_tr'):
    if lang == 'tr':
        return item.get(key_tr) or item.get(key_en) or ''
    return item.get(key_en) or ''


def _cat(svc, lang='tr'):
    # Service/category names always in English for consistency
    return svc.get('category_en') or svc.get('service', '')


# WAFR code → AWS doc URL
_WAFR_DOC_BASE = {
    'SEC':  'https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/welcome.html',
    'OPS':  'https://docs.aws.amazon.com/wellarchitected/latest/operational-excellence-pillar/welcome.html',
    'REL':  'https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/welcome.html',
    'PERF': 'https://docs.aws.amazon.com/wellarchitected/latest/performance-efficiency-pillar/welcome.html',
    'COST': 'https://docs.aws.amazon.com/wellarchitected/latest/cost-optimization-pillar/welcome.html',
    'SUS':  'https://docs.aws.amazon.com/wellarchitected/latest/sustainability-pillar/welcome.html',
}


def _wafr_url(code):
    m = _re.match(r'^([A-Z]+)', code)
    pillar = m.group(1) if m else ''
    return _WAFR_DOC_BASE.get(pillar, '#')


def _wafr_link(code):
    url = _wafr_url(code)
    return f'<a class="wafr-code" href="{url}" target="_blank" rel="noopener" title="{code}">{code}</a>'


# ═══════════════════════════════════════════════════════════════════════════════
# HTML helpers — build content for one language
# ═══════════════════════════════════════════════════════════════════════════════

def _build_service_nav(services, lang):
    """Build nav links for one language."""
    prefix = 'en' if lang == 'en' else 'tr'
    lines = []
    for idx, svc in enumerate(services, 1):
        cat = _cat(svc, lang)
        svc_id = f'svc-{prefix}-{idx}'
        fc = len(svc.get('findings', []))
        pc = len(svc.get('positive', []))
        bcls = 'has-findings' if fc else ('all-pass' if pc else '')
        bval = fc if fc else (f'\u2713{pc}' if pc else '0')
        lines.append(
            f'<a class="nav-link" href="#{svc_id}">'
            f'<span style="flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">{idx}. {cat}</span>'
            f'<span class="count-badge {bcls}">{bval}</span></a>'
        )
    return '\n'.join(lines)


def _build_body(results, lang):
    """Build the main body HTML for one language."""
    profile = results.get('profile', 'unknown')
    account_id = results.get('account_id', '')
    assess_time = results.get('assessment_time', '')
    summary = results.get('summary', {})
    services = results.get('services', [])
    pillar_scores = results.get('pillar_scores', {})
    risk = summary.get('risk_counts', {})

    h = ''
    # Meta
    h += f'''<table class="meta-table">
      <tr><td class="label">{_t('profile',lang)}:</td><td class="value">{profile}</td></tr>
      <tr><td class="label">{_t('account',lang)}:</td><td class="value" style="color:#c2410c">{account_id}</td></tr>
      <tr><td class="label">{_t('date',lang)}:</td><td class="value">{assess_time}</td></tr>
    </table>'''

    # Summary
    h += f'<h2 class="section-title" id="summary">{_t("summary",lang)}</h2>'
    h += f'''<div class="summary-grid">
      <div class="summary-card"><div class="val val-high">{risk.get("HIGH",0)}</div><div class="lbl">{_t("high_risk",lang)}</div></div>
      <div class="summary-card"><div class="val val-medium">{risk.get("MEDIUM",0)}</div><div class="lbl">{_t("medium_risk",lang)}</div></div>
      <div class="summary-card"><div class="val val-low">{risk.get("LOW",0)}</div><div class="lbl">{_t("low_risk",lang)}</div></div>
      <div class="summary-card"><div class="val val-pos">{summary.get("total_positive",0)}</div><div class="lbl">{_t("positive",lang)}</div></div>
      <div class="summary-card"><div class="val val-svc">{summary.get("services_analyzed",0)}</div><div class="lbl">{_t("services",lang)}</div></div>
    </div>'''

    # Pillar scores
    h += f'<h2 class="section-title" id="pillars">{_t("pillar_scores",lang)}</h2>'
    h += '<table class="pillar-table"><thead><tr>'
    h += f'<th>{_t("pillar",lang)}</th><th>{_t("score",lang)}</th><th>{_t("findings",lang)}</th><th>{_t("positive",lang)}</th></tr></thead><tbody>'
    for code, info in pillar_scores.items():
        pn = info.get('name_tr','') if lang=='tr' else info.get('name_en',code)
        sc = info.get('score',0)
        bc = '#dc2626' if sc<30 else '#d97706' if sc<60 else '#16a34a'
        h += f'<tr><td style="font-weight:600">{pn}</td>'
        h += f'<td style="font-weight:700;color:{bc}">{sc}% <span class="pillar-bar"><span class="pillar-bar-fill" style="width:{sc}%;background:{bc}"></span></span></td>'
        h += f'<td>{info.get("findings",0)}</td><td>{info.get("positive",0)}</td></tr>'
    h += '</tbody></table>'

    # Service sections
    prefix = 'en' if lang == 'en' else 'tr'
    for idx, svc in enumerate(services, 1):
        cat = _cat(svc, lang)
        findings = svc.get('findings', [])
        recs = svc.get('recommendations', [])
        positive = svc.get('positive', [])

        h += f'<h2 class="section-title" id="svc-{prefix}-{idx}">{idx}. {cat}</h2>'

        if findings:
            h += f'<h3 class="sub-heading finding">{_t("tespitler",lang)}: ({len(findings)})</h3>'
            h += '<ul class="findings-list">'
            for f in findings:
                rv = f.get('risk','LOW')
                txt = _txt(f, lang)
                codes = ' '.join(_wafr_link(c) for c in f.get('wafr_codes',[]))
                meta = []
                if f.get('region'): meta.append(f['region'])
                if f.get('resource_id'): meta.append(f['resource_id'])
                ms = f' <span style="color:var(--text-meta);font-size:9pt">({", ".join(meta)})</span>' if meta else ''
                lc = rv.lower() if rv in ('MEDIUM','LOW') else ''
                h += f'<li class="{lc}"><span class="risk-badge risk-{rv}">{rv}</span>{codes}{ms}<br>{txt}</li>'
            h += '</ul>'

        if recs:
            h += f'<h3 class="sub-heading rec">{_t("oneriler",lang)}: ({len(recs)})</h3>'
            h += '<ul class="rec-list">'
            for r in recs:
                txt = _txt(r, lang)
                codes = ' '.join(_wafr_link(c) for c in r.get('wafr_codes',[]))
                h += f'<li>{txt} {codes}</li>'
            h += '</ul>'

        if positive:
            h += f'<h3 class="sub-heading pos">{_t("olumlu",lang)}: ({len(positive)})</h3>'
            h += '<ul class="pos-list">'
            for p in positive:
                h += f'<li>&#10003; {_txt(p, lang)}</li>'
            h += '</ul>'

    h += f'<div class="footer">{_t("generated_by",lang)} &mdash; {assess_time}</div>'
    return h


# ═══════════════════════════════════════════════════════════════════════════════
# HTML Report — Bilingual (TR/EN toggle) + Dark/Light toggle
# ═══════════════════════════════════════════════════════════════════════════════

_CSS_HTML = """
@media print {
  body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .page-break { page-break-before: always; }
  .no-print, .nav-sidebar { display: none !important; }
  .main-content { margin-left: 0 !important; max-width: 100% !important; }
}
* { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }

/* ── CSS Variables (Light default — matches original hardcoded values) ── */
:root {
  --bg-page: #f1f5f9; --bg-content: #fff; --bg-card: #f8fafc;
  --bg-nav: #0f1b2d; --text-primary: #1a1a1a; --text-secondary: #334155;
  --text-muted: #64748b; --text-meta: #64748b; --border: #e2e8f0;
  --accent: #ff9900; --nav-border: #1e3a5f;
  --heading-color: #0f1b2d;
  --finding-bg: #fef2f2; --finding-border: #dc2626;
  --medium-bg: #fffbeb; --medium-border: #d97706;
  --low-bg: #f0fdf4; --low-border: #65a30d;
  --pos-bg: #f0fdf4; --pos-border: #16a34a;
  --pillar-head: #1e3a5f; --pillar-alt: #f8fafc;
  --wafr-bg: #fff7ed; --wafr-color: #c2410c; --wafr-border: #fed7aa;
}
[data-theme="dark"] {
  --bg-page: #0b1120; --bg-content: #111827; --bg-card: #1e293b;
  --text-primary: #e2e8f0; --text-secondary: #94a3b8;
  --text-muted: #64748b; --text-meta: #64748b; --border: #1e3a5f;
  --heading-color: #e2e8f0;
  --finding-bg: #1c1012; --medium-bg: #1c1808; --low-bg: #0c1a0f;
  --pos-bg: #0c1a0f;
  --pillar-head: #1e3a5f; --pillar-alt: #1e293b;
  --wafr-bg: #1e1510; --wafr-color: #fb923c; --wafr-border: #92400e;
}
body {
  font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
  font-size: 11pt;
  line-height: 1.6;
  color: var(--text-primary);
  background: var(--bg-page);
}
/* ── Toolbar ── */
.toolbar {
  position: fixed; top: 0; right: 0; z-index: 200;
  display: flex; gap: 4px; padding: 8px 12px;
  background: var(--bg-nav); border-bottom-left-radius: 8px;
}
.toolbar button {
  background: #1e293b; border: 1px solid #475569; color: #cbd5e1;
  padding: 4px 10px; border-radius: 4px; font-size: 9pt; font-weight: 600;
  cursor: pointer; transition: all .15s;
}
.toolbar button:hover {
  background: #334155; color: #f1f5f9; border-color: #94a3b8;
}
.toolbar button.active {
  background: var(--accent); color: #000; border-color: var(--accent);
}
/* ── Sticky Navigation Sidebar ── */
.nav-sidebar {
  position: fixed;
  top: 0; left: 0;
  width: 240px;
  height: 100vh;
  overflow-y: auto;
  background: var(--bg-nav);
  color: #cbd5e1;
  padding: 16px 0;
  font-size: 9pt;
  z-index: 100;
  border-right: 2px solid var(--accent);
}
.nav-sidebar::-webkit-scrollbar { width: 4px; }
.nav-sidebar::-webkit-scrollbar-thumb { background: #334155; border-radius: 2px; }
.nav-logo {
  padding: 0 16px 14px;
  border-bottom: 1px solid var(--nav-border);
  margin-bottom: 10px;
}
.nav-logo .logo-text { font-size: 13pt; font-weight: 800; color: var(--accent); }
.nav-logo .logo-sub { font-size: 8pt; color: #64748b; margin-top: 2px; }
.nav-section-label {
  font-size: 7.5pt; text-transform: uppercase; letter-spacing: 1px;
  color: #475569; font-weight: 700; padding: 10px 16px 4px;
}
.nav-link {
  display: flex; align-items: center; gap: 8px;
  padding: 6px 16px; color: #94a3b8; text-decoration: none;
  transition: all .15s; border-left: 3px solid transparent;
  font-size: 9pt; line-height: 1.4;
}
.nav-link:hover { background: #1e293b; color: #e2e8f0; border-left-color: #334155; }
.nav-link.active { background: #1e293b; color: var(--accent); border-left-color: var(--accent); font-weight: 600; }
.nav-link .count-badge {
  margin-left: auto; background: #1e3a5f; color: #94a3b8;
  font-size: 8pt; padding: 1px 6px; border-radius: 8px; font-weight: 600;
}
.nav-link .count-badge.has-findings { background: #dc262630; color: #fca5a5; }
.nav-link .count-badge.all-pass { background: #16a34a30; color: #86efac; }
/* ── Main Content ── */
.main-content {
  margin-left: 240px;
  max-width: 1200px;
  padding: 24px 32px 60px;
  background: var(--bg-content);
  min-height: 100vh;
}
@media (max-width: 900px) {
  .nav-sidebar { display: none; }
  .main-content { margin-left: 0; padding: 16px; }
}
h1 {
  font-size: 20pt; color: var(--heading-color);
  border-bottom: 3px solid var(--accent);
  padding-bottom: 8px; margin-bottom: 6px;
}
h2.section-title {
  font-size: 16pt; color: var(--heading-color);
  margin-top: 28px; margin-bottom: 14px;
  padding-top: 12px; padding-bottom: 4px;
  border-bottom: 2px solid var(--border);
  scroll-margin-top: 16px;
}
h3.sub-heading {
  font-size: 11pt; font-weight: 700;
  margin-top: 16px; margin-bottom: 8px;
}
h3.sub-heading.finding { color: #b91c1c; }
h3.sub-heading.rec     { color: #047857; }
h3.sub-heading.pos     { color: #15803d; }
.meta-table {
  width: 100%; border-collapse: collapse;
  margin-bottom: 20px; font-size: 10pt;
}
.meta-table td { padding: 4px 12px 4px 0; vertical-align: top; }
.meta-table .label { color: var(--text-muted); font-weight: 600; width: 140px; }
.meta-table .value { color: var(--heading-color); font-weight: 700; }
.summary-grid {
  display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 20px;
}
.summary-card {
  background: var(--bg-card); border: 1px solid var(--border);
  border-radius: 6px; padding: 12px 18px;
  min-width: 110px; flex: 1; text-align: center;
}
.summary-card .val { font-size: 22pt; font-weight: 800; line-height: 1.2; }
.summary-card .lbl {
  font-size: 8pt; color: var(--text-muted);
  text-transform: uppercase; letter-spacing: .5px; margin-top: 2px;
}
.val-high   { color: #dc2626; }
.val-medium { color: #d97706; }
.val-low    { color: #65a30d; }
.val-pos    { color: #16a34a; }
.val-svc    { color: #2563eb; }
.pillar-table {
  width: 100%; border-collapse: collapse;
  margin-bottom: 20px; font-size: 10pt;
}
.pillar-table th {
  background: var(--pillar-head); color: #fff;
  padding: 8px 12px; text-align: left; font-weight: 600;
}
.pillar-table td { padding: 7px 12px; border-bottom: 1px solid var(--border); }
.pillar-table tr:nth-child(even) td { background: var(--pillar-alt); }
.pillar-bar {
  display: inline-block; height: 8px; border-radius: 4px;
  background: var(--border); width: 120px; vertical-align: middle; margin-left: 8px;
}
.pillar-bar-fill { display: block; height: 100%; border-radius: 4px; }
ul.findings-list { list-style: none; padding: 0; margin: 0 0 12px 0; }
ul.findings-list li {
  margin-bottom: 8px; padding: 8px 12px;
  background: var(--finding-bg); border-left: 3px solid var(--finding-border);
  border-radius: 0 4px 4px 0; font-size: 10.5pt; line-height: 1.6;
}
ul.findings-list li.medium { background: var(--medium-bg); border-left-color: var(--medium-border); }
ul.findings-list li.low { background: var(--low-bg); border-left-color: var(--low-border); }
ul.rec-list { list-style: disc; padding-left: 20px; margin: 0 0 12px 0; }
ul.rec-list li { margin-bottom: 6px; font-size: 10.5pt; line-height: 1.6; }
ul.pos-list { list-style: none; padding: 0; margin: 0 0 12px 0; }
ul.pos-list li {
  margin-bottom: 4px; padding: 5px 12px;
  background: var(--pos-bg); border-left: 3px solid var(--pos-border);
  border-radius: 0 4px 4px 0; font-size: 10pt; line-height: 1.5;
}
.wafr-code {
  display: inline-block; background: var(--wafr-bg); color: var(--wafr-color);
  font-size: 9pt; font-weight: 700; padding: 0 5px;
  border-radius: 3px; border: 1px solid var(--wafr-border); margin-right: 3px;
  text-decoration: none; transition: background .15s;
}
a.wafr-code:hover { background: var(--wafr-border); }
.risk-badge {
  display: inline-block; color: #fff; font-size: 8pt;
  font-weight: 700; padding: 1px 8px; border-radius: 3px; margin-right: 6px;
}
.risk-HIGH   { background: #dc2626; }
.risk-MEDIUM { background: #d97706; }
.risk-LOW    { background: #65a30d; }
.footer {
  margin-top: 40px; padding-top: 12px;
  border-top: 1px solid var(--border);
  font-size: 9pt; color: #94a3b8; text-align: center;
}
.lang-content { display: none; }
.lang-content.active { display: block; }
"""


def generate_html(results: dict, ts: str = None) -> str:
    """Generate bilingual HTML report with TR/EN + dark/light toggles."""
    ts = ts or _ts()
    profile = results.get('profile', 'unknown')
    services = results.get('services', [])

    # Build both language bodies
    body_tr = _build_body(results, 'tr')
    body_en = _build_body(results, 'en')

    # Build nav for both languages
    nav_tr = _build_service_nav(services, 'tr')
    nav_en = _build_service_nav(services, 'en')

    js = """
<script>
let _lang = 'tr';
let _theme = 'light';

let _observer = null;

function setLang(lang) {
  _lang = lang;
  document.querySelectorAll('.lang-content').forEach(el => {
    el.classList.toggle('active', el.dataset.lang === lang);
  });
  document.querySelectorAll('.nav-services').forEach(el => {
    el.style.display = el.dataset.lang === lang ? '' : 'none';
  });
  document.querySelectorAll('.lang-btn').forEach(b => b.classList.toggle('active', b.dataset.lang === lang));
  document.getElementById('navTitle').textContent = lang === 'tr'
    ? 'AWS Well-Architected Degerlendirme Raporu'
    : 'AWS Well-Architected Assessment Report';
  document.getElementById('navSummaryLabel').textContent = lang === 'tr' ? 'Yonetici Ozeti' : 'Executive Summary';
  document.getElementById('navSummaryLink').textContent = lang === 'tr' ? 'Yonetici Ozeti' : 'Executive Summary';
  document.getElementById('navPillarLink').textContent = lang === 'tr' ? 'WAFR Sutun Skorlari' : 'WAFR Pillar Scores';
  document.getElementById('navServicesLabel').textContent = lang === 'tr'
    ? 'Analiz Edilen Servisler (' + SERVICES_COUNT + ')'
    : 'Services Analyzed (' + SERVICES_COUNT + ')';
  // Reinitialize scroll spy for new language
  setTimeout(initScrollSpy, 50);
}

function setTheme(theme) {
  _theme = theme;
  document.documentElement.setAttribute('data-theme', theme);
  document.querySelectorAll('.theme-btn').forEach(b => b.classList.toggle('active', b.dataset.theme === theme));
}

// Scroll spy + smooth scroll click
function initScrollSpy() {
  if (_observer) _observer.disconnect();
  // Get only visible nav links
  const visibleNav = document.querySelector('.nav-services[data-lang="' + _lang + '"]') ||
                     document.querySelector('.nav-services:not([style*="display:none"])');
  const navLinks = visibleNav ? visibleNav.querySelectorAll('.nav-link[href^="#"]') : [];
  const fixedLinks = document.querySelectorAll('.nav-sidebar > .nav-link[href^="#"]');
  const allLinks = [...fixedLinks, ...navLinks];
  const sections = [];
  allLinks.forEach(l => {
    const id = l.getAttribute('href').slice(1);
    const el = document.getElementById(id);
    if (el) sections.push({el, link: l});
  });
  if (!sections.length) return;
  _observer = new IntersectionObserver(entries => {
    entries.forEach(e => {
      if (e.isIntersecting) {
        allLinks.forEach(l => l.classList.remove('active'));
        const m = sections.find(s => s.el === e.target);
        if (m) m.link.classList.add('active');
      }
    });
  }, {rootMargin: '-10% 0px -80% 0px'});
  sections.forEach(s => _observer.observe(s.el));
}

// Smooth scroll on nav link click
document.addEventListener('click', function(e) {
  const link = e.target.closest('.nav-link[href^="#"]');
  if (!link) return;
  e.preventDefault();
  const id = link.getAttribute('href').slice(1);
  const el = document.getElementById(id);
  if (el) el.scrollIntoView({behavior: 'smooth', block: 'start'});
});

document.addEventListener('DOMContentLoaded', () => { initScrollSpy(); });
</script>"""

    svc_count = len(services)

    html = f"""<!DOCTYPE html>
<html lang="tr"><head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_t('report_title','tr')} — {profile}</title>
<style>{_CSS_HTML}</style>
</head><body>

<!-- Toolbar: Lang + Theme toggles -->
<div class="toolbar no-print">
  <button class="lang-btn active" data-lang="tr" onclick="setLang('tr')">TR</button>
  <button class="lang-btn" data-lang="en" onclick="setLang('en')">EN</button>
  <span style="width:8px"></span>
  <button class="theme-btn active" data-theme="light" onclick="setTheme('light')">&#9728;</button>
  <button class="theme-btn" data-theme="dark" onclick="setTheme('dark')">&#9790;</button>
</div>

<!-- Navigation Sidebar -->
<nav class="nav-sidebar">
  <div class="nav-logo">
    <div class="logo-text">ScanBox</div>
    <div class="logo-sub" id="navTitle">{_t('report_title','tr')}</div>
  </div>
  <div class="nav-section-label" id="navSummaryLabel">{_t('summary','tr')}</div>
  <a class="nav-link" href="#summary" id="navSummaryLink">{_t('summary','tr')}</a>
  <a class="nav-link" href="#pillars" id="navPillarLink">{_t('pillar_scores','tr')}</a>
  <div class="nav-section-label" id="navServicesLabel" style="margin-top:8px">{_t('services','tr')} ({svc_count})</div>
  <div class="nav-services" data-lang="tr">{nav_tr}</div>
  <div class="nav-services" data-lang="en" style="display:none">{nav_en}</div>
</nav>

<!-- Main Content -->
<div class="main-content">
  <h1 class="lang-content active" data-lang="tr">{_t('report_title','tr')}</h1>
  <h1 class="lang-content" data-lang="en">{_t('report_title','en')}</h1>
  <div class="lang-content active" data-lang="tr">{body_tr}</div>
  <div class="lang-content" data-lang="en">{body_en}</div>
</div>

<script>const SERVICES_COUNT = {svc_count};</script>
{js}
</body></html>"""

    filename = f'advice_{profile}_{ts}.html'
    filepath = os.path.join(REPORTS_DIR, filename)
    with open(filepath, 'w', encoding='utf-8') as fh:
        fh.write(html)
    return filename


# ═══════════════════════════════════════════════════════════════════════════════
# PDF Report — Professional A4 Portrait (ReportLab)
# ═══════════════════════════════════════════════════════════════════════════════

def generate_pdf(results: dict, ts: str = None, lang: str = 'tr') -> str:
    """Generate a single PDF in the specified language."""
    ts = ts or _ts()
    profile = results.get('profile', 'unknown')
    services = results.get('services', [])
    summary = results.get('summary', {})
    pillar_scores = results.get('pillar_scores', {})
    risk = summary.get('risk_counts', {})

    filename = f'advice_{profile}_{ts}_{lang}.pdf'
    filepath = os.path.join(REPORTS_DIR, filename)

    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.enums import TA_CENTER
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            HRFlowable,
        )
        from reportlab.lib.units import mm
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont

        # Register Unicode-capable fonts for Turkish characters (ş,ç,ğ,ı,ö,ü,İ,Ş,Ç,Ğ)
        _font_paths = {
            'Arial':     ['/System/Library/Fonts/Supplemental/Arial.ttf',
                          '/Library/Fonts/Arial Unicode.ttf',
                          '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'],
            'ArialBold': ['/System/Library/Fonts/Supplemental/Arial Bold.ttf',
                          '/Library/Fonts/Arial Unicode.ttf',
                          '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],
        }
        _font_registered = False
        for fname, paths in _font_paths.items():
            for p in paths:
                if os.path.isfile(p):
                    try:
                        pdfmetrics.registerFont(TTFont(fname, p))
                        _font_registered = True
                        break
                    except Exception:
                        continue

        _fn = 'Arial' if _font_registered else 'Helvetica'
        _fnb = 'ArialBold' if _font_registered else 'Helvetica-Bold'

        doc = SimpleDocTemplate(
            filepath, pagesize=A4,
            topMargin=20*mm, bottomMargin=20*mm,
            leftMargin=18*mm, rightMargin=18*mm,
        )

        styles = getSampleStyleSheet()
        s_title = ParagraphStyle('RTitle', parent=styles['Title'],
                                 fontName=_fnb, fontSize=18,
                                 textColor=colors.HexColor('#0f1b2d'), spaceAfter=4)
        s_h2 = ParagraphStyle('RH2', parent=styles['Heading2'],
                               fontName=_fnb, fontSize=14,
                               textColor=colors.HexColor('#0f1b2d'),
                               spaceBefore=16, spaceAfter=8)
        s_h3f = ParagraphStyle('RH3F', parent=styles['Heading3'],
                                fontName=_fnb, fontSize=11,
                                textColor=colors.HexColor('#b91c1c'),
                                spaceBefore=10, spaceAfter=4)
        s_h3r = ParagraphStyle('RH3R', parent=styles['Heading3'],
                                fontName=_fnb, fontSize=11,
                                textColor=colors.HexColor('#047857'),
                                spaceBefore=10, spaceAfter=4)
        s_h3p = ParagraphStyle('RH3P', parent=styles['Heading3'],
                                fontName=_fnb, fontSize=11,
                                textColor=colors.HexColor('#15803d'),
                                spaceBefore=10, spaceAfter=4)
        s_bullet = ParagraphStyle('RBullet', parent=styles['Normal'],
                                   fontName=_fn, fontSize=9, leading=13,
                                   leftIndent=12, bulletIndent=0,
                                   spaceBefore=3, spaceAfter=3)
        s_footer = ParagraphStyle('RFooter', parent=styles['Normal'],
                                   fontName=_fn, fontSize=7, leading=9,
                                   textColor=colors.HexColor('#94a3b8'),
                                   alignment=TA_CENTER)

        elements = []

        # Title
        elements.append(Paragraph(_t('report_title', lang), s_title))
        elements.append(HRFlowable(width='100%', thickness=2,
                                    color=colors.HexColor('#ff9900'), spaceAfter=8))

        # Meta
        meta_data = [
            [_t('profile',lang)+':', profile],
            [_t('account',lang)+':', results.get('account_id','')],
            [_t('date',lang)+':', results.get('assessment_time','')],
        ]
        mt = Table(meta_data, colWidths=[110, None])
        mt.setStyle(TableStyle([
            ('FONTSIZE',(0,0),(-1,-1),9),
            ('TEXTCOLOR',(0,0),(0,-1),colors.HexColor('#64748b')),
            ('FONTNAME',(0,0),(0,-1),_fnb),
            ('FONTNAME',(1,0),(1,-1),_fnb),
            ('VALIGN',(0,0),(-1,-1),'TOP'),
            ('BOTTOMPADDING',(0,0),(-1,-1),2),
        ]))
        elements.append(mt)
        elements.append(Spacer(1, 10*mm))

        # Summary
        elements.append(Paragraph(_t('summary',lang), s_h2))
        sd = [[
            f"{_t('high_risk',lang)}\n{risk.get('HIGH',0)}",
            f"{_t('medium_risk',lang)}\n{risk.get('MEDIUM',0)}",
            f"{_t('low_risk',lang)}\n{risk.get('LOW',0)}",
            f"{_t('positive',lang)}\n{summary.get('total_positive',0)}",
            f"{_t('services',lang)}\n{summary.get('services_analyzed',0)}",
        ]]
        st = Table(sd, colWidths=[None]*5)
        st.setStyle(TableStyle([
            ('ALIGN',(0,0),(-1,-1),'CENTER'), ('FONTSIZE',(0,0),(-1,-1),9),
            ('FONTNAME',(0,0),(-1,-1),_fn),
            ('BOX',(0,0),(-1,-1),0.5,colors.HexColor('#e2e8f0')),
            ('INNERGRID',(0,0),(-1,-1),0.5,colors.HexColor('#e2e8f0')),
            ('BACKGROUND',(0,0),(-1,-1),colors.HexColor('#f8fafc')),
            ('TOPPADDING',(0,0),(-1,-1),8), ('BOTTOMPADDING',(0,0),(-1,-1),8),
        ]))
        elements.append(st)
        elements.append(Spacer(1, 6*mm))

        # Pillar scores
        elements.append(Paragraph(_t('pillar_scores',lang), s_h2))
        pd = [[_t('pillar',lang), _t('score',lang), _t('findings',lang), _t('positive',lang)]]
        for code, info in pillar_scores.items():
            pn = info.get('name_tr','') if lang=='tr' else info.get('name_en',code)
            pd.append([pn, f"{info.get('score',0)}%", str(info.get('findings',0)), str(info.get('positive',0))])
        pt = Table(pd, colWidths=[None, 60, 60, 60])
        pt.setStyle(TableStyle([
            ('BACKGROUND',(0,0),(-1,0),colors.HexColor('#1e3a5f')),
            ('TEXTCOLOR',(0,0),(-1,0),colors.white),
            ('FONTNAME',(0,0),(-1,0),_fnb),
            ('FONTNAME',(0,1),(-1,-1),_fn),
            ('FONTSIZE',(0,0),(-1,-1),9),
            ('GRID',(0,0),(-1,-1),0.5,colors.HexColor('#e2e8f0')),
            ('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#f8fafc')]),
            ('TOPPADDING',(0,0),(-1,-1),6), ('BOTTOMPADDING',(0,0),(-1,-1),6),
        ]))
        elements.append(pt)
        elements.append(Spacer(1, 8*mm))

        # Service sections
        for idx, svc in enumerate(services, 1):
            cat = _cat(svc, lang)
            findings = svc.get('findings',[])
            recs = svc.get('recommendations',[])
            positive = svc.get('positive',[])

            elements.append(Paragraph(f'{idx}. {cat}', s_h2))

            if findings:
                elements.append(Paragraph(f'<b>{_t("tespitler",lang)} ({len(findings)})</b>', s_h3f))
                for f in findings:
                    rv = f.get('risk','LOW')
                    txt = _txt(f, lang)
                    codes = ', '.join(f.get('wafr_codes',[]))
                    meta = []
                    if f.get('region'): meta.append(f['region'])
                    if f.get('resource_id'): meta.append(f['resource_id'])
                    ms = f' ({", ".join(meta)})' if meta else ''
                    bt = f'<b>[{rv}]</b> {txt}{"  ("+codes+")" if codes else ""}{ms}'
                    elements.append(Paragraph(f'<bullet>&bull;</bullet>{bt}', s_bullet))

            if recs:
                elements.append(Paragraph(f'<b>{_t("oneriler",lang)} ({len(recs)})</b>', s_h3r))
                for r in recs:
                    txt = _txt(r, lang)
                    codes = ', '.join(r.get('wafr_codes',[]))
                    bt = f'{txt}{"  ("+codes+")" if codes else ""}'
                    elements.append(Paragraph(f'<bullet>&bull;</bullet>{bt}', s_bullet))

            if positive:
                elements.append(Paragraph(f'<b>{_t("olumlu",lang)} ({len(positive)})</b>', s_h3p))
                for p in positive[:10]:
                    elements.append(Paragraph(f'<bullet>&#10003;</bullet>{_txt(p,lang)}', s_bullet))

            elements.append(Spacer(1, 4*mm))

        # Footer
        elements.append(Spacer(1, 10*mm))
        elements.append(HRFlowable(width='100%', thickness=0.5, color=colors.HexColor('#e2e8f0')))
        elements.append(Spacer(1, 3*mm))
        elements.append(Paragraph(
            f'{_t("generated_by",lang)} &mdash; {results.get("assessment_time","")}', s_footer))

        doc.build(elements)

    except ImportError:
        with open(filepath, 'w', encoding='utf-8') as fh:
            fh.write(f'PDF generation requires reportlab. Profile: {profile}')

    return filename


# ═══════════════════════════════════════════════════════════════════════════════
# Generate All — HTML (bilingual) + PDF-TR + PDF-EN  (shared timestamp)
# ═══════════════════════════════════════════════════════════════════════════════

def generate_all(results: dict, **kwargs) -> dict:
    """Generate HTML (bilingual) + PDF-TR + PDF-EN with shared timestamp."""
    ts = _ts()
    return {
        'html':   generate_html(results, ts),
        'pdf_tr': generate_pdf(results, ts, 'tr'),
        'pdf_en': generate_pdf(results, ts, 'en'),
    }
